# Generated by Django 2.2.7 on 2019-12-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextypegoodsbanner',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='展示顺序'),
        ),
    ]
